name: Close inactive issues
on:
  schedule:
    - cron: "30 21 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 14
          stale-issue-label: "stale"
          stale-issue-message: "This issue has been marked as stale because it has been inactive for more than 30 days."
          close-issue-message: "This issue has been automatically closed because it has been marked as stale for over 14 days without any activity."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
